owner: bitmama-reply
repo: uptimemonitor

sites:
  - name: Antonia IT
    url: https://www.antonia.it/it
  - name: Antonia US
    url: https://www.antonia.it/us/
  - name: Nexi AEM HP
    url: https://www.nexi.it/shop
  - name: Nexi Configuratore SmartPOS
    url: https://www.nexi.it/shop/cart/smartpos.html?m=wifi
  - name: Zegna Group
    url: https://www.zegnagroup.com/it/
  - name: Zegna Forest
    url: https://zegnaforest.fondazionezegna.org/it/  
 - name: Giro D'Italia
    url: https://www.giroditalia.it/
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptimemonitor
  logoUrl: https://www.bitmama.it/Style%20Library/bitmama/img/bitmama-reply-new.png
  name: Bitmama Uptime Monitor
  introTitle: "**Bitmama** uptime monitoring"
  introMessage: Uptime live monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
